@extends('MainSite.index')
@section('content')
    @include('MainSite.Common.CatWithBanner')
    @include('MainSite.Common.RandomProductsSlider')
    @include('MainSite.Common.FeaturedProducts')
    @include('MainSite.Common.AdsBanner')
    @include('MainSite.Common.LatestProductThreeSlider')
    @include('MainSite.Common.FromTheblogs')
@endsection
